//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nSoft.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nSoft.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server address is not correct!.
        /// </summary>
        internal static string CONNECTION_STATUS_ADDRESS_ERROR {
            get {
                return ResourceManager.GetString("CONNECTION_STATUS_ADDRESS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed!.
        /// </summary>
        internal static string CONNECTION_STATUS_ERROR {
            get {
                return ResourceManager.GetString("CONNECTION_STATUS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect server!.
        /// </summary>
        internal static string CONNECTION_STATUS_SERVER_ERROR {
            get {
                return ResourceManager.GetString("CONNECTION_STATUS_SERVER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string DATA_REQUESTED {
            get {
                return ResourceManager.GetString("DATA_REQUESTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string DATA_RESPONSED {
            get {
                return ResourceManager.GetString("DATA_RESPONSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database not connected!.
        /// </summary>
        internal static string DATABASE_NOT_CONNECTED {
            get {
                return ResourceManager.GetString("DATABASE_NOT_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect format!.
        /// </summary>
        internal static string JSON_PARSE_ERROR {
            get {
                return ResourceManager.GetString("JSON_PARSE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app.nsofts@gmail.com.
        /// </summary>
        internal static string MAIL_ADDRESS {
            get {
                return ResourceManager.GetString("MAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is report file for your request..
        /// </summary>
        internal static string MAIL_CONTENT {
            get {
                return ResourceManager.GetString("MAIL_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enzfjehxouzrmxbs.
        /// </summary>
        internal static string MAIL_PWD {
            get {
                return ResourceManager.GetString("MAIL_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp.gmail.com.
        /// </summary>
        internal static string MAIL_SERVER {
            get {
                return ResourceManager.GetString("MAIL_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nSofts Laundromat System.
        /// </summary>
        internal static string MAIL_TITLE {
            get {
                return ResourceManager.GetString("MAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nSofts Manager.
        /// </summary>
        internal static string MAIL_USER {
            get {
                return ResourceManager.GetString("MAIL_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running but cannot access web service.
        /// </summary>
        internal static string NO_SERVER {
            get {
                return ResourceManager.GetString("NO_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service running.
        /// </summary>
        internal static string RUNNING {
            get {
                return ResourceManager.GetString("RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service stopped.
        /// </summary>
        internal static string STOPPED {
            get {
                return ResourceManager.GetString("STOPPED", resourceCulture);
            }
        }
    }
}
